### PR TITLE
Upgrade to hawkular-bus 0.5.0.Final

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@Jiri-Kremser would you please review and eventually merge?

**Comment by jkremser** [comment]
^

``` bash
Compilation failure: Compilation failure:
[ERROR] /home/travis/build/hawkular/hawkular-inventory/hawkular-inventory-bus-api/src/main/java/org/hawkular/inventory/bus/api/InventoryEventMessageListener.java:[45,5] method does not override or implement a method from a supertype
[ERROR] /home/travis/build/hawkular/hawkular-inventory/hawkular-inventory-bus-api/src/main/java/org/hawkular/inventory/bus/api/InventoryEventMessageListener.java:[49,25] cannot find symbol
[ERROR] symbol: method getBasicMessageFromMessage(javax.jms.Message)
```

**Comment by metlos** [comment]
@ppalaga I created a PR on your branch that should fix the failure.

**Comment by ppalaga** [comment]
@metlos thanks, merged

**Pull request merged**
