### PR TITLE
Javadocs in API. Yay!

### PR DESCRIPTION
**Pull request by metlos**
Mostly just comments.
Code changes:
- specific exceptions thrown from ReadInterface#get and WriteInterface#delete and WriteInterface#update
- Related.Direction renamed to EntityRole and its members from IN, OUT, ANY to TARGET, SOURCE, ANY to better express what they do.

### CODE REVIEW

**Comment by jkremser** [comment]
lgtm :+1:

**Comment by metlos** [comment]
Force-pushed the PR branch rebased on latest future branch.

**Comment by metlos** [comment]
wow, so that didn't quite work.. lemme redo it..

**Comment by jkremser** [comment]
:feelsgood:

**Comment by metlos** [comment]
another try

**Comment by jkremser** [comment]
:shipit: (trying http://www.emoji-cheat-sheet.com/)

**Pull request merged**
