### PR TITLE
HWKINVENT-97 | API removed dependency on GSON

### PR DESCRIPTION
**Pull request by pavolloffay**

### CODE REVIEW

**Comment by jkremser** [comment]
looks good, but you've probably missed these ones:

``` bash
$git grep "gson"
bus-api/pom.xml:      <groupId>com.google.code.gson</groupId>
bus-api/pom.xml:      <artifactId>gson</artifactId>
bus-api/pom.xml:      <version>${version.com.google.code.gson}</version>
bus-api/src/main/java/org/hawkular/inventory/bus/api/EnvironmentEvent.java:import com.google.gson.annotations.Expose;
bus-api/src/main/java/org/hawkular/inventory/bus/api/FeedEvent.java:import com.google.gson.annotations.Expose;
bus-api/src/main/java/org/hawkular/inventory/bus/api/InventoryEvent.java:import com.google.gson.annotations.Expose;
bus-api/src/main/java/org/hawkular/inventory/bus/api/MetricEvent.java:import com.google.gson.annotations.Expose;
bus-api/src/main/java/org/hawkular/inventory/bus/api/MetricTypeEvent.java:import com.google.gson.annotations.Expose;
bus-api/src/main/java/org/hawkular/inventory/bus/api/RelationshipEvent.java:import com.google.gson.annotations.Expose;
bus-api/src/main/java/org/hawkular/inventory/bus/api/ResourceEvent.java:import com.google.gson.annotations.Expose;
bus-api/src/main/java/org/hawkular/inventory/bus/api/ResourceTypeEvent.java:import com.google.gson.annotations.Expose;
bus-api/src/main/java/org/hawkular/inventory/bus/api/TenantEvent.java:import com.google.gson.annotations.Expose;
```

EDIT: I see the 

> "We should remove the dependency on gson from the api module and remove any annotations from the code."

..in the Jira, but perhaps we should remove it completelly, or does bus still require gson? It shouldn't care about the serialization technology, provided it's valid JSON, right?

**Comment by pavolloffay** [comment]
I wasn't sure about the bus-api. I will try to remove it form there too.

**Comment by metlos** [comment]
While we're at it, I think bus impl will need some testing... I am not sure it depends on the `hawkular-inventory-json-helper` so I am not sure if it serializes all the inventory data correctly.

**Comment by jkremser** [comment]
I've tested it and haven't seen any exceptions in the server log

**Pull request merged**
