### PR TITLE
Introduce Inventory feature pack to ease the installation of inventory into Wildfly.

### PR DESCRIPTION
**Pull request by metlos**
Also, in a separate commit, itests updated to take advantage of the feature pack.

### CODE REVIEW

**Comment by metlos** [comment]
@ppalaga would you please have a look at this? travis is acting up, this builds just fine locally.

**Comment by ppalaga** [comment]
The FP plugin fails if the `src/main/resources/modules` directory is not there in the FP module. Just run `echo "wildfly-feature-pack-plugin fails if src/main/resources/modules does not exist" > hawkular-inventory-feature-pack/src/main/resources/modules/README.adoc` from to top inventory folder to make git aware of the directory.

**Comment by ppalaga** [comment]
With the named changes, I can build locally, and the itests pass. The first review round is thus finished.

**Comment by metlos** [comment]
@ppalaga - updated according to your comments.. Would you please review again?

**Pull request merged**
