### PR TITLE
HAWKULAR-1138 move to okhttp 3.x

### PR DESCRIPTION
**Pull request by jmazzitelli**

### CODE REVIEW

**Comment by metlos** [comment]
The build is failing because it can't find the version for okhttp dependency. Possibly because 51-SNAPSHOT of hawkular-parent that was used during the build doesn't define it yet?

**Comment by jmazzitelli** [comment]
Yes. See the JIRA. None of these are going to pass until we release parent-pom. We need to orchestrate all the merges here - first parent-pom, then commons, then the rest. 

I just need the code to be peer reviewed. Once done. We'll release parent-pom, and then the rest will follow.

**Comment by jotak** [comment]
Does it require to update also the dep. version of commons? If yes I'll need also to push an update about cors filters

**Comment by jmazzitelli** [comment]
H-Commons is going to be updated as part of this okhttp upgrade - see https://github.com/hawkular/hawkular-commons/pull/94

**Comment by metlos** [comment]
so we will need to consume that new version, too, in our parent pom.

**Comment by jmazzitelli** [comment]
I tried moving to the latest commons but got these errors - which I guess is related to @jotak  comment about needing to fix the cors stuff - what do I need to do to fix this?
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project hawkular-inventory-rest-api: Compilation failure: Compilation failure:
[ERROR] /home/mazz/source/hawkular-inventory/hawkular-inventory-rest-api/src/main/java/org/hawkular/inventory/rest/interceptors/CorsFilter.java:[27,38] cannot find symbol
[ERROR] symbol:   class AbstractCorsResponseFilter
[ERROR] location: package org.hawkular.jaxrs.filter.cors
[ERROR] /home/mazz/source/hawkular-inventory/hawkular-inventory-rest-api/src/main/java/org/hawkular/inventory/rest/interceptors/CorsFilter.java:[28,38] cannot find symbol
[ERROR] symbol:   class AbstractOriginValidation
[ERROR] location: package org.hawkular.jaxrs.filter.cors
[ERROR] /home/mazz/source/hawkular-inventory/hawkular-inventory-rest-api/src/main/java/org/hawkular/inventory/rest/interceptors/CorsFilter.java:[38,33] cannot find symbol
[ERROR] symbol: class AbstractCorsResponseFilter
[ERROR] /home/mazz/source/hawkular-inventory/hawkular-inventory-rest-api/src/main/java/org/hawkular/inventory/rest/interceptors/CorsFilter.java:[68,57] cannot find symbol
[ERROR] symbol:   class AbstractOriginValidation
[ERROR] location: class org.hawkular.inventory.rest.interceptors.CorsFilter
```

**Comment by jotak** [comment]
I just pushed my PR. You can merge it in yours, it's here: https://github.com/hawkular/hawkular-inventory/pull/323

**Comment by jmazzitelli** [comment]
Since PR #323 is separate from this okhttp upgrade, we'll leave that PR separate and merge it separate. We'll do it first then I'll rebase my PR on it and merge that. We'll do all of this when the time comes - I still need peer review on the rest of my PRs and be given a thumbs up to upgrade okhttp and release parent-pom first.

**Comment by metlos** [comment]
#323 is merged so we're free to move on with this when time is ready.

**Comment by jotak** [comment]
LGTM

**Comment by metlos** [comment]
K, so now we have to wait for parent and commons releases to update this PR with before merging...

**Comment by jmazzitelli** [comment]
> K, so now we have to wait for parent and commons releases to update this PR with before merging...

Correct. Once I do that, I will rebase and get this PR to go green.

**Comment by metlos** [comment]
Merged. Thanks, @jmazzitelli!

**Pull request merged**
