### PR TITLE
HAWKULAR-585 - Updated Accounts - Cassandra datastore

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by metlos** [comment]
```
12:31:43,649 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC000001: Failed to start service jboss.module.service."deployment.hawkular-accounts.war".main: org.jboss.msc.service.StartException in service jboss.module.service."deployment.hawkular-accounts.war".main: WFLYSRV0179: Failed to load module: deployment.hawkular-accounts.war:main

    at org.jboss.as.server.moduleservice.ModuleLoadService.start(ModuleLoadService.java:91)

    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)

    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)

    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

    at java.lang.Thread.run(Thread.java:745)

Caused by: org.jboss.modules.ModuleNotFoundException: com.datastax.cassandra:main

    at org.jboss.modules.Module.addPaths(Module.java:1042)

    at org.jboss.modules.Module.link(Module.java:1398)

    at org.jboss.modules.Module.relinkIfNecessary(Module.java:1426)

    at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:238)

    at org.jboss.as.server.moduleservice.ModuleLoadService.start(ModuleLoadService.java:68)

    ... 5 more

```

Does this require some packaging changes to dist? We have a "dist-like" distribution that packages embedded cassandra, inventory rest-api and accounts to provide for minimal testing deployment but the new accounts fail to start in it.

**Comment by jpkrohling** [comment]
Yes, it requires the Datastax driver deployed as a module. 
The module is available here: https://github.com/hawkular/hawkular/tree/master/modules/nest/cassandra-driver-wf-module

This is how we include it on nest: https://github.com/hawkular/hawkular/blob/master/modules/nest/hawkular-nest-distro/pom.xml#L147-L158

Alternatively, you could try to use the nest-distro , which includes these and the bus stuff: 
https://github.com/hawkular/hawkular/tree/master/modules/nest/hawkular-nest-distro

**Comment by metlos** [comment]
I'm afraid that won't be that simple, because it would introduce a circular dependency between hawkular/hawkular and hawkular/inventory repos.

**Comment by metlos** [comment]
what prevents the cassandra driver from being in commons repo?

**Comment by jpkrohling** [comment]
The driver is now at commons:
https://github.com/hawkular/hawkular-commons/tree/master/cassandra-driver-wf-module

**Comment by jpkrohling** [comment]
By the way, the account's dependency on the driver is set to "provided", so, your WAR/EAR would have to list this module in its dependency list. It's either done via manifest entries or jboss-deployment-structure.xml

**Comment by jpkrohling** [comment]
So, I changed a couple of other things before I hit a dependency hell. It seems that tinkerpop needs guava 16.0, whereas the Cassandra driver needs 18.0, and they seem to be incompatible:

```
Caused by: java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class com.thinkaurelius.titan.graphdb.database.idassigner.StandardIDPool$IDBlockRunnable
```

**Comment by jpkrohling** [comment]
To solve the problem mentioned before, I added the driver to the WAR. I'm keeping the part where the driver is deployed as a module, as it still represents how the hawkular distribution looks like.

**Comment by metlos** [comment]
Thank you, Juca!

**Pull request merged**
