### PR TITLE
Sqlg bump + optimizations

### PR DESCRIPTION
**Pull request by metlos**
Sqlg internals have some range filtering improvements and other general perf improvements.

There's also a gremlin traversal generation optimization in inventory.

Overall we should see better performance with this update.

### CODE REVIEW

**Comment by jotak** [comment]
You had to rollback a sqlg bump previously, is it right? (the thing about light artifacts). The issue you had is now fixed?

**Comment by metlos** [comment]
Hmm... I don't know why Travis is failing this... All is passing locally.
But yes, the issues we had with the previous update seem to have been resolved. But I'm marking this as "don't merge yet" to investigate the failure...

**Comment by metlos** [comment]
Heh. So things worked for me locally, because the code before the latest commit in this PR depended on the wrong sqlg artifact that brought in a snapshot version of the dialect that I built locally and that worked.

Reintroducing the "slimming" commit fixed inv to depend on the correct artifacts and so this passes on Travis now, too.

**Comment by metlos** [comment]
Hmm.. so I see the errors about the cached plan again when connected to postgres.. Need to investigate this...

**Comment by metlos** [comment]
@jotak could you please take another look at this?

**Comment by jotak** [comment]
LGTM

**Pull request merged**
