### PR TITLE
Tenant in headers

### PR DESCRIPTION
**Pull request by metlos**
Following the suite of metrics, the tenant is now read from the headers, or rather using accounts in whatever way it chooses.

### CODE REVIEW

**Comment by jkremser** [comment]
Once this is merged it'd break the UI. I can prepare the UI for this change or ping someone, before merging.

**Comment by metlos** [comment]
UI depends on inventory 0.0.9 while this will go into 0.1.0. We can merge now and prepare the UI later. It would be good to create a UI JIRA for that though...

**Comment by jkremser** [comment]
It looks good, providing the following code returns really the current persona and not some stale data:

``` java
RestBase:
    protected String getTenantId() {
        return personas.getCurrent().getId();
    }
```

EDIT:
it takes the current persona from the (hopefully)current http request

``` java
String personaId = this.httpRequest.getHeader("Hawkular-Persona")
```

**Comment by jkremser** [comment]
> UI depends on inventory 0.0.9 while this will go into 0.1.0. We can merge now and prepare the UI later. It would be good to create a UI JIRA for that though...

right

**Comment by metlos** [comment]
As for obtaining the current persona - there are more ways of doing that in accounts, so we can choose another if this somehow breaks. Btw. the `getTenantId()` method is already in 0.0.9 with the same impl.

**Pull request merged**
