### PR TITLE
[HWKINVENT-177] Re-establish the newly created entity caching to improve performance.

### PR DESCRIPTION
**Pull request by metlos**

### CODE REVIEW

**Comment by jkremser** [comment]
``` bash
[jkremser@localhost hawkular-inventory pr240]🏃 m clean install -Pitest
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:21 min
[INFO] Finished at: 2016-04-13T16:17:31+02:00
[INFO] Final Memory: 195M/565M
```

**Comment by ppalaga** [comment]
Gentlemen, the Travis build in this PR is failing in tinkerpop-tinkergraph-provider tests [1] - that is much earlier than the PR that upgraded to Cassandra 3.4 [2]. I am afraid, I can reproduce the failure [1] locally.

[1] https://travis-ci.org/hawkular/hawkular-inventory/builds/122775577#L3697
[2] https://travis-ci.org/hawkular/hawkular-inventory/builds/121652532#L7163

**Comment by jkremser** [comment]
@ppalaga hmm.. it's still passing for me, try to run it locally

EDIT: oh, you've already built it locally

**Comment by jkremser** [comment]
now, I've reproduced

**Pull request merged**
