### PR TITLE
HAWKULAR-877 - Enabled the Secret Store

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jkremser** [comment]
Does it accept bitcoins? :)

**Comment by jpkrohling** [comment]
Darn, you found the _real_ meaning of the secret store :/

**Comment by jkremser** [comment]
I knew it! :)

meme

**Comment by metlos** [comment]
what's this for may I ask?

**Comment by metlos** [comment]
other than mine bitcoin and establish new world order, obviously... :)

**Comment by jpkrohling** [comment]
It's so that inventory's backend can accept a token:secret (generated by the "Tokens" screen), in addition to Bearer tokens and username/password

**Pull request merged**
