### PR TITLE
Take the subsystems.xml and template.xml unchanged or transformed from the depen

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@metlos could you please review and eventually merge?

**Comment by ppalaga** [comment]
@metlos strange enough, it is passing here locally running with `-Pitest,ltest`. Do you have any idea what is Travis not liking about this PR?

**Comment by ppalaga** [comment]
@metlos It is passing now. I wonder if anything relevant has changed in master?

**Comment by metlos** [comment]
Yes, #233 has been merged, which made some corrections that made itests and load tests much less noisy (and the impl more correct).

**Pull request merged**
