### PR TITLE
Unit tests for CanonicalPaths containing the escaped characters.

### PR DESCRIPTION
**Pull request by jkremser**
~~**tests only**~~

~~This will obviously fail the travis build~~

UPDATE: The implementation made by @metlos has landed to this PR

### CODE REVIEW

**Comment by metlos** [comment]
Ok, now there's the question of who of the two of us should merge this :smile:

**Comment by metlos** [comment]
@ppalaga could you do an overall review and merge if ok, pls?

**Comment by jkremser** [comment]
On the hawkular lvl, the issue is still there.. investigating..

**Comment by jkremser** [comment]
merging myself as it's needed for hawkular master to work without errors and no one with push rights is currently online

**Comment by jkremser** [comment]
@metlos here is the itest https://github.com/hawkular/hawkular/tree/dev/esc

I believe it corresponds to what hawkular-agent currently sends in here http://git.io/vYK60 I.e. in the json payload it's the basic `x.replaceAll("/", "\\\\/")` and in the URL it's `Util.urlEncode(x.replaceAll("/", "\\\\/"))`

**Comment by jkremser** [comment]
It looks like we can have the better control of how the url is decoded by resteasy by using [UriInfo.getPath(false)](https://docs.oracle.com/javaee/7/api/javax/ws/rs/core/UriInfo.html#getPath-boolean-).

**Pull request merged**
