### PR TITLE
Upgrade to Cassandra 3.4 via hawkular-parent 40, use custom Titan 0.5.4-jboss-1

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@metlos could you please review and eventually merge?

**Comment by ppalaga** [comment]
@metlos I restarted Travis to see if the failures are reproducible. FWIW, all tests are passing here locally.

**Comment by ppalaga** [comment]
0146750 just eliminates the stack traces starting with `InvalidQueryException: Index ..._idx_1 …` that were harmless anyway.

**Comment by metlos** [comment]
Trying to restart the build once more... Travis is acting up again and doesn't want to start cassandra...

**Comment by jkremser** [comment]
Just for the record, I did 1 restart yesterday around midnight with no success.

btw. what about this?:

```
[WARNING] Failed to resolve old artifacts: Failed to resolve version for org.hawkular.inventory:hawkular-inventory-paths:jar:RELEASE: Could not find metadata org.hawkular.inventory:hawkular-inventory-paths/maven-metadata.xml in jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public-jboss/). The API analysis will not proceed.
```

is it the rev-api saying there is nothing to compare with?

It's pretty tricky to find out why the embedded C\* don't start, there are no logs. If only there was a way to ssh to the failed build..

**Comment by metlos** [comment]
Seems to me that in the last run, C\* was shot down mid-flight - half of the integration tests passed and the other half got connection exceptions...

**Comment by metlos** [comment]
> btw. what about this?:
> 
> [WARNING] Failed to resolve old artifacts: Failed to resolve version for org.hawkular.inventory:hawkular-inventory-paths:jar:RELEASE: Could not find metadata org.hawkular.inventory:hawkular-inventory-paths/maven-metadata.xml in jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public-jboss/). The API analysis will not proceed.
> 
> is it the rev-api saying there is nothing to compare with?

Yes.

**Pull request merged**
