### PR TITLE
When creating a resource with some additional metadata stored in the pro...

### PR DESCRIPTION
**Pull request by jkremser**
...perties hash, it was ignored.

### CODE REVIEW

**Comment by metlos** [comment]
Huh, did the very same thing, only for all entity types in #48 ;)

**Comment by jkremser** [comment]
ouch, me 2 :]

**Comment by jkremser** [comment]
lol, it's almost the same

**Comment by metlos** [comment]
After discussing with Jirka, I'm closing this in favor of #48. Thanks for the effort and confirming the approach ;)

**Pull request closed without merging**
